### ISSUE TITLE
boom build failing

### ISSUE THREAD

**Issue by joe-getcouragenow** [go-boom/boom#1]
am running this on your blog repo..

any ideas ?

````

cd /Users/apple/workspace/go/src/github.com/joe-getcouragenow/dev/exp/doc/boom/blog && /Users/apple/workspace/go/src/github.com/joe-getcouragenow/dev/exp/doc/boom/bin/boom build .
INFO[0000] cleaning output dir                          
INFO[0000] copying assets                               
INFO[0000] copying themes                               
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x17a6e4d]

goroutine 1 [running]:
github.com/RadhiFadlillah/boom/internal/cmd.copyThemes.func3(0x1895a95, 0x1, 0x0, 0x0, 0x20c24c0, 0xc00023c3c0, 0x0, 0x1)
        /Users/apple/workspace/go/src/github.com/joe-getcouragenow/dev/exp/doc/boom/boom/internal/cmd/build.go:288 +0x6d
path/filepath.Walk(0xc00002c540, 0x5e, 0xc00063f8b0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/path/filepath/path.go:404 +0x6b
github.com/RadhiFadlillah/boom/internal/cmd.copyThemes(0xc00002c780, 0x50, 0xc00002c840, 0x57, 0x0, 0x0)
        /Users/apple/workspace/go/src/github.com/joe-getcouragenow/dev/exp/doc/boom/boom/internal/cmd/build.go:286 +0x3c5
github.com/RadhiFadlillah/boom/internal/cmd.buildHandler(0xc00026db80, 0xc0001e3000, 0x1, 0x1)
        /Users/apple/workspace/go/src/github.com/joe-getcouragenow/dev/exp/doc/boom/boom/internal/cmd/build.go:60 +0x2e5
github.com/spf13/cobra.(*Command).execute(0xc00026db80, 0xc0001e2fd0, 0x1, 0x1, 0xc00026db80, 0xc0001e2fd0)
        /Users/apple/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00026cdc0, 0x0, 0x0, 0x0)
        /Users/apple/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/apple/workspace/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/apple/workspace/go/src/github.com/joe-getcouragenow/dev/exp/doc/boom/boom/main.go:9 +0x2a
make: *** [ex-build] Error 2
````

**Comment by RadhiFadlillah** [comment]
I forgot to check error in `filepath.Walk`. It should be fixed by 8d66981.
